-- Temporary Supabase setup for frontend-direct mode
-- Run in Supabase SQL Editor once

-- Main complaints table
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_token VARCHAR(50) UNIQUE NOT NULL,
  reporter_name VARCHAR(255) NOT NULL,
  reporter_email VARCHAR(255) NOT NULL,
  reporter_phone VARCHAR(20) NOT NULL,
  aadhaar_number VARCHAR(12),
  pan_number VARCHAR(10),
  address_line1 TEXT NOT NULL,
  address_line2 TEXT,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  pincode VARCHAR(10) NOT NULL,
  nearest_police_station VARCHAR(255) NOT NULL,
  incident_date DATE NOT NULL,
  incident_type VARCHAR(100) NOT NULL,
  incident_description TEXT NOT NULL,
  suspect_information TEXT,
  evidence_details TEXT,
  financial_loss DECIMAL(15, 2) DEFAULT 0,
  submission_date TIMESTAMPTZ DEFAULT NOW(),
  status VARCHAR(50) DEFAULT 'pending',
  pdf_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- OTP table
CREATE TABLE IF NOT EXISTS public.otp_verification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_number VARCHAR(50) NOT NULL,
  contact VARCHAR(255) NOT NULL,
  method VARCHAR(10) NOT NULL,
  otp_code VARCHAR(6) NOT NULL,
  expiry_time TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(token_number, contact)
);

-- Complaint updates
CREATE TABLE IF NOT EXISTS public.complaint_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_token VARCHAR(50) NOT NULL,
  update_date TIMESTAMPTZ DEFAULT NOW(),
  update_message TEXT NOT NULL,
  updated_by VARCHAR(100),
  CONSTRAINT fk_complaint_updates_token
    FOREIGN KEY (complaint_token)
    REFERENCES public.complaints(complaint_token)
    ON DELETE CASCADE
);

-- Evidence files
CREATE TABLE IF NOT EXISTS public.evidence_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_token VARCHAR(50) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  file_size BIGINT,
  file_type VARCHAR(50),
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_evidence_files_token
    FOREIGN KEY (complaint_token)
    REFERENCES public.complaints(complaint_token)
    ON DELETE CASCADE
);

-- Resolved complaints
CREATE TABLE IF NOT EXISTS public.resolved_complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_token VARCHAR(50) UNIQUE NOT NULL,
  resolution_date DATE NOT NULL,
  resolution_status VARCHAR(50) NOT NULL,
  resolution_description TEXT NOT NULL,
  action_taken TEXT NOT NULL,
  CONSTRAINT fk_resolved_complaints_token
    FOREIGN KEY (complaint_token)
    REFERENCES public.complaints(complaint_token)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_complaints_token ON public.complaints(complaint_token);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON public.complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_email ON public.complaints(reporter_email);
CREATE INDEX IF NOT EXISTS idx_otp_token_contact ON public.otp_verification(token_number, contact);
CREATE INDEX IF NOT EXISTS idx_updates_token ON public.complaint_updates(complaint_token);

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_complaints_updated_at'
  ) THEN
    CREATE TRIGGER update_complaints_updated_at
    BEFORE UPDATE ON public.complaints
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();
  END IF;
END$$;

-- Temporary RLS policies for anon frontend access
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_verification ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resolved_complaints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tmp_complaints_all ON public.complaints;
CREATE POLICY tmp_complaints_all ON public.complaints
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS tmp_otp_all ON public.otp_verification;
CREATE POLICY tmp_otp_all ON public.otp_verification
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS tmp_updates_all ON public.complaint_updates;
CREATE POLICY tmp_updates_all ON public.complaint_updates
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS tmp_evidence_all ON public.evidence_files;
CREATE POLICY tmp_evidence_all ON public.evidence_files
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS tmp_resolved_all ON public.resolved_complaints;
CREATE POLICY tmp_resolved_all ON public.resolved_complaints
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);
